services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FORCE_SSL=false
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    profiles:
      - donotstart # Desactivamos Caddy en local, no hace falta
